name: Build and Deploy Productcatalogue 

on:
  push:
    branches:
      - master
    paths:
      - 'productcatalogue/**'
      
permissions:
  contents: write
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '8'

      - name: Build and Deploy productcatalogue
        working-directory: productcatalogue
        run: |
          mvn clean install 
          docker build -t halouani/productcatalogue:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images to Docker Hub
        run: docker push halouani/productcatalogue:latest

      - name: Create and Push Dynamic Git Tag
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch --tags

          # Récupère le dernier tag ou initialise à v1.0.0
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")

          echo "Dernier tag: $LAST_TAG"

          # Extrait la partie numérique 
          VERSION=${LAST_TAG#v}

          # Incrémente le patch 
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "Nouveau tag: $NEW_TAG"

          # Configuration Git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag $NEW_TAG
          git push origin $NEW_TAG
      

          
